### ISSUE TITLE
ThemeSwitcher (Il y'a un premier bug 😂)

### ISSUE THREAD

**Issue by bruxx-6243** [PossaCode-Community/PossaCode_Website#6]
Salut la team @MakVieSAinte  @Lafonddeboumas @ruthelie @sancty007 @jovyzabel !
J'espère que vous vous portez bien, alors avez-vous tester le site de votre côté?

**Comment by bruxx-6243** [comment]
J'ai fixé le bug même si personne n'a tenté ne serait-ce regarder. 🤣

**Comment by sancty007** [comment]
t'inquiète j'essaie de regarder

**Comment by sancty007** [comment]
j'ai vu l'ajout du Z-index , c'est ça ?
